### ISSUE TITLE
No match found for location with path

### ISSUE THREAD

**Issue by chenxi-chenjia** [gmingchen/vue3-element-plus-admin#11]
您好，在您的项目中，当使用了动态添加路由，跳转至动态添加的路由页面之后，刷新该页面，首先会弹出一个路由不匹配的警告，请问如何解决。

**Comment by gmingchen** [comment]
有相关步骤 或者 图片吗

**Comment by gmingchen** [comment]
> 您好，在您的项目中，当使用了动态添加路由，跳转至动态添加的路由页面之后，刷新该页面，首先会弹出一个路由不匹配的警告，请问如何解决。

有相关步骤 或者 图片吗

**Comment by chenxi-chenjia** [comment]
![image](https://user-images.githubusercontent.com/23130578/123727488-4eabbe80-d8c4-11eb-97ef-8d7704ff37f8.png)
<img width="1428" alt="WechatIMG188" src="https://user-images.githubusercontent.com/23130578/123727574-6f741400-d8c4-11eb-8139-5e8d72733887.png">

**Comment by gmingchen** [comment]
你是在什么情况下出现这种现象，我这边是没有出现这种情况的

**Comment by chenxi-chenjia** [comment]
我下载了你的项目，在权限动态加载路由的时候，进入动态夹杂的路由，然后刷新页面，就会出现这种情况

**Comment by gmingchen** [comment]
> 我下载了你的项目，在权限动态加载路由的时候，进入动态夹杂的路由，然后刷新页面，就会出现这种情况

这好像只要使用了动态加载路由就会出现这个警告，也有人在vue-router 提了这个问题，但是没有解决，但是这个不影响！

**Comment by chenxi-chenjia** [comment]
我试着在加载动态路由之前先重置路由，然后重新生成路由，这样可以解决这个警告，但不知道这样会有什么异常影响。

**Comment by gmingchen** [comment]
可以可以，这很优秀。我估摸着后面应该会修复这个问题的吧
