### ISSUE TITLE
菜单可以给个overflow-x:auto

### ISSUE THREAD

**Issue by Ljy0826** [gmingchen/vue3-element-plus-admin#31]
![image](https://user-images.githubusercontent.com/53161048/185284783-99a2359e-1d75-475e-aba0-9de0ec255ade.png)

**Comment by Ljy0826** [comment]
同时将滚动条隐藏
![image](https://user-images.githubusercontent.com/53161048/185285525-3072b37a-164c-4d9d-a3c8-7d514c835964.png)

**Comment by gmingchen** [comment]
已处理这个问题，使用element-plus标签页组件自带的形式

**Comment by Ljy0826** [comment]
邮件已到达！辛苦你了！

**Comment by Ljy0826** [comment]
邮件已到达！辛苦你了！
