### ISSUE TITLE
npm install报错npm install npm ERR! Invalid Version: 0.1.0a2

### ISSUE THREAD

**Issue by zmy1014** [gmingchen/vue3-element-plus-admin#32]
npm ERR! Invalid Version: 0.1.0a2

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ws001\AppData\Local\npm-cache\_logs\2022-09-09T01_32_47_497Z-debug-0.log

**Comment by Dakka11** [comment]
版本号不能有字母？

**Comment by gmingchen** [comment]
应该是你环境的问题
