### ISSUE TITLE
添加菜单权限这个功能我用了demo系列账号登录都没有看到

### ISSUE THREAD

**Issue by RanY-Luck** [gmingchen/vue3-element-plus-admin#33]
![image](https://user-images.githubusercontent.com/67427627/209893688-0b2986c9-f6d6-48d0-ba9f-640087fa0d0d.png)

**Comment by gmingchen** [comment]
![image](https://user-images.githubusercontent.com/39894090/210510004-92140ce7-0500-485e-a819-c6bad166643a.png)
这属于开发时候的配置，演示帐号不开放出来
